{ config, pkgs, lib, ... }:

let
  homeDir = config.home.homeDirectory or builtins.getEnv "HOME";
in

{
  # Compositor and Wayland-specific packages and configs
  home.packages = with pkgs; [
    hyprland
    waybar
    mako
    wl-clipboard
    grim
    slurp
    xdg-desktop-portal
    xdg-desktop-portal-wlr
  ];

  # Compositor config (minimal example)
  home.file.".config/hypr/hyprland.conf" = {
    text = ''
# Minimal Hyprland config generated by home-manager
monitor=eDP-1,1920x1080@60,0x0
exec=waybar
exec=mako

# wallpaper (user should replace with their own path)
wallpaper = ${homeDir}/.config/hypr/wallpaper.jpg

# animations
animations=1

# floating windows (examples)
windowrulev2 = float,workspace=1,app_id=^pavucontrol$

# keybindings (example: super+enter to spawn terminal)
bind=SUPER+ENTER,exec,foot
'';
  };

  # Provide a placeholder wallpaper file (may not exist on all systems)
  home.file.".config/hypr/wallpaper.jpg" = {
    source = ''/run/current-system/sw/share/backgrounds/gnome/adwaita-day.jpg'';
  };

  # Session variables for Wayland
  home.sessionVariables = {
    XDG_CURRENT_DESKTOP = "Hyprland";
    GDK_BACKEND = "wayland";
    QT_QPA_PLATFORM = "wayland";
    CLUTTER_BACKEND = "wayland";
  };

  # Mako notification style (synthwave palette)
  home.file.".config/mako/style.css" = {
    text = ''
window {
  background: rgba(11,15,26,0.95);
  color: #E6E6FA;
  border-radius: 8px;
  border: 1px solid rgba(124,77,255,0.12);
}
.header { color: #FF6AC1; }
.body { color: #E6E6FA; }
.actions .button { background: rgba(124,77,255,0.06); color: #FF8A00; }
'';
  };
}
